from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    DATABASE_URL: str
    CORS_ORIGINS: str | None = None
    REDIS_URL: str | None = None
    MARKETLY_SOURCE_TIMEOUT_SECONDS: float = 18.0
    MARKETLY_FACEBOOK_SOURCE_TIMEOUT_SECONDS: float = 20.0
    MARKETLY_FACEBOOK_SOURCE_TIMEOUT_SECONDS_SINGLE_SOURCE: float = 35.0
    MARKETLY_FACEBOOK_MAX_FETCH_LIMIT: int = 12
    MARKETLY_MULTI_SOURCE_MAX_EXPANSIONS: int = 4
    MARKETLY_DISABLE_FACEBOOK_MULTI_SOURCE_EXPANSION: bool = True
    MARKETLY_BALANCE_MULTI_SOURCE_RESULTS: bool = True
    SUPABASE_JWT_SECRET: str | None = None
    SUPABASE_URL: str | None = None
    SUPABASE_ANON_KEY: str | None = None
    SUPABASE_SERVICE_ROLE_KEY: str | None = None
    SUPABASE_LISTINGS_TABLE: str = "listings"
    MARKETLY_ENABLE_FACEBOOK: bool = False
    MARKETLY_FACEBOOK_AUTH_MODE: str = "guest"
    MARKETLY_FACEBOOK_COOKIE_PATH: str = "secrets/fb_cookies.json"
    MARKETLY_FACEBOOK_RETRIES: int = 1
    MARKETLY_FACEBOOK_TIMEOUT_SECONDS: float = 20.0
    MARKETLY_FACEBOOK_IDLE_SCROLL_LIMIT: int = 2
    MARKETLY_FACEBOOK_IDLE_SCROLL_LIMIT_SINGLE_SOURCE: int = 5
    MARKETLY_FACEBOOK_MAX_SCROLLS: int = 12
    MARKETLY_FACEBOOK_MAX_SCROLLS_SINGLE_SOURCE: int = 40
    MARKETLY_FACEBOOK_MAX_CONCURRENCY: int = 1
    MARKETLY_FACEBOOK_BOOTSTRAP_HOME: bool = False
    MARKETLY_FACEBOOK_JITTER_MIN_SECONDS: float = 0.08
    MARKETLY_FACEBOOK_JITTER_MAX_SECONDS: float = 0.25
    MARKETLY_FACEBOOK_OVERFETCH_BUFFER: int = 6
    MARKETLY_FACEBOOK_OVERFETCH_BUFFER_MULTI_SOURCE: int = 2
    MARKETLY_FACEBOOK_MAX_SCRAPE_LIMIT: int = 32
    MARKETLY_FACEBOOK_MAX_SCRAPE_LIMIT_SINGLE_SOURCE: int = 120
    MARKETLY_RESPONSE_CACHE_ENABLED: bool = True
    MARKETLY_RESPONSE_CACHE_TTL_SECONDS: int = 45
    MARKETLY_RESPONSE_CACHE_LOCAL_FALLBACK_ENABLED: bool = True
    MARKETLY_RESPONSE_CACHE_LOCAL_MAX_ITEMS: int = 24
    MARKETLY_RATE_LIMIT_ENABLED: bool = True
    MARKETLY_RATE_LIMIT_FAIL_OPEN: bool = True
    MARKETLY_RATE_LIMIT_LOCAL_FALLBACK_ENABLED: bool = True
    MARKETLY_RATE_LIMIT_LOCAL_MAX_KEYS: int = 5000
    MARKETLY_RATE_LIMIT_SEARCH_IP_PER_MIN: int = 60
    MARKETLY_RATE_LIMIT_SEARCH_USER_PER_MIN: int = 30
    MARKETLY_RATE_LIMIT_SAVED_MUTATION_PER_MIN: int = 20
    MARKETLY_RATE_LIMIT_FB_COOKIE_PUT_PER_HOUR: int = 6
    MARKETLY_RATE_LIMIT_FB_VERIFY_PER_HOUR: int = 12
    MARKETLY_RATE_LIMIT_FB_DELETE_PER_HOUR: int = 20
    MARKETLY_SEARCH_FETCH_CACHE_MAX_ITEMS: int = 32
    MARKETLY_SEARCH_PAGINATION_CACHE_MAX_ITEMS: int = 8
    MARKETLY_CREDENTIALS_ENCRYPTION_KEY: str | None = None
    EBAY_ENV: str = "production"
    EBAY_CLIENT_ID: str | None = None
    EBAY_CLIENT_SECRET: str | None = None
    EBAY_MARKETPLACE_ID: str = "EBAY_CA"
    EBAY_ACCEPT_LANGUAGE: str = "en-CA"
    EBAY_SCOPE: str = "https://api.ebay.com/oauth/api_scope"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="allow",
    )

    ENV: str = "dev"
    CACHE_TTL_SECONDS: int = 60


settings = Settings()
